server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/participacion_ciudadana
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
  issuer: conectaciudad
  secret: ${JWT_SECRET}
services:
  grupo2:
    base-url: https://conecta-ciudad-api.azurewebsites.net/
  grupo1:
    base-url: https://conecta-ciudad-api-2.azurewebsites.net/
